name: data_walker
description: A library to supply sequential or random objects within the given range and repeats.
version: 0.2.3
homepage: https://aiurovet.com/
repository: https://github.com/aiurovet/data_walker/

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  random_unicode: ^0.2.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
