name: data_walker
description: A library to supply all or random indices of a list or within a range.
version: 0.1.0
homepage: https://aiurovet.blogspot.com/

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
