name: data_walker
description: A library to supply sequential or random objects within the given range and repeats.
version: 0.1.1
homepage: https://aiurovet.blogspot.com/
repository: https://github.com/aiurovet/data_walker/

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
